## MostafaZamaniturk

## Part 1 of the Assignment:

Creating and Exploring Tensors

In [ ]:
# Download the libraries
! pip install tensorflow
! pip install torch

In [4]:
# Check the version of TensorFlow
! pip show tensorflow
# Check the version of PyTorch
! pip show torch


Name: tensorflow
Version: 2.20.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /Users/mostafazamaniturk/.venvs/py313/lib/python3.13/site-packages
Requires: absl-py, astunparse, flatbuffers, gast, google_pasta, grpcio, h5py, keras, libclang, ml_dtypes, numpy, opt_einsum, packaging, protobuf, requests, setuptools, six, tensorboard, termcolor, typing_extensions, wrapt
Required-by: 
Name: torch
Version: 2.8.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3-Clause
Location: /Users/mostafazamaniturk/.venvs/py313/lib/python3.13/site-packages
Requires: filelock, fsspec, jinja2, networkx, setuptools, sympy, typing-extensions
Required-by: accelerate, inFairness, sentence-transformers, torchviz


In [5]:
# Import libraries

# TensorFlow
import tensorflow as tf

# PyTorch
import torch

1.1 Create one-dimensional tensors in both TensorFlow and PyTorch, each containing at least 5 values of your choice. Print the tensors and their shapes.

In [15]:
# Create a one-dimensional tensor in TensorFlow
tensor_tf_1d = tf.constant([1, 2, 3, 4, 5])

print("TensorFlow Tensor:")
print(tensor_tf_1d)
print("Shape of TensorFlow Tensor:")
print(tensor_tf_1d.shape)
print("--------------------------------")
# Create a one-dimensional tensor in PyTorch
tensor_pt_1d = torch.tensor([1, 2, 3, 4, 5])

print("PyTorch Tensor:")
print(tensor_pt_1d)
print("Shape of PyTorch Tensor:")
print(tensor_pt_1d.shape)




TensorFlow Tensor:
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
Shape of TensorFlow Tensor:
(5,)
--------------------------------
PyTorch Tensor:
tensor([1, 2, 3, 4, 5])
Shape of PyTorch Tensor:
torch.Size([5])


1.2. Create two-dimensional tensors (matrices) in both frameworks with dimensions of at least 3×4. Print the tensors and their shapes.

In [ ]:
# Create a two-dimensional tensor in TensorFlow
tensor_tf_2d = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("TensorFlow Tensor:")
print(tensor_tf_2d)
print("Shape of TensorFlow Tensor:")
print(tensor_tf_2d.shape)
print("--------------------------------")
# Create a two-dimensional tensor in PyTorch
tensor_pt_2d = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("PyTorch Tensor:")
print(tensor_pt_2d)
print("Shape of PyTorch Tensor:")
print(tensor_pt_2d.shape)



TensorFlow Tensor:
tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)
Shape of TensorFlow Tensor:
(3, 4)
--------------------------------
PyTorch Tensor:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
Shape of PyTorch Tensor:
torch.Size([3, 4])


1.3. Create three-dimensional tensors in both frameworks with dimensions of your choice. Print the tensors and their shapes, and demonstrate indexing by accessing specific elements.

In [29]:
# Create a three-dimensional tensor in TensorFlow
tensor_tf_3d = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print("TensorFlow Tensor:")
print(tensor_tf_3d)
print("Shape of TensorFlow Tensor:")
print(tensor_tf_3d.shape)

print("--------------------------------")

# Create a three-dimensional tensor in PyTorch
tensor_pt_3d = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print("PyTorch Tensor:")
print(tensor_pt_3d)
print("Shape of PyTorch Tensor:")
print(tensor_pt_3d.shape)

print("--------------------------------")

# Access specific elements
print("Accessing specific elements:")
print("TensorFlow:")
print(tensor_tf_3d[0, 1, 2])  # Access the element at position (0, 1, 2)
print(tensor_tf_3d[1, 1, 1])  # Access the element at position (1, 1, 1)


print("--------------------------------")

print("PyTorch:")
print(tensor_pt_3d[0, 1, 2])  # Access the element at position (0, 1, 2)
print(tensor_pt_3d[1, 1, 1])  # Access the element at position (1, 1, 1)


print("--------------------------------")



TensorFlow Tensor:
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
Shape of TensorFlow Tensor:
(2, 2, 3)
--------------------------------
PyTorch Tensor:
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
Shape of PyTorch Tensor:
torch.Size([2, 2, 3])
--------------------------------
Accessing specific elements:
TensorFlow:
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(11, shape=(), dtype=int32)
--------------------------------
PyTorch:
tensor(6)
tensor(11)
--------------------------------


1.4. Create a function in both TensorFlow and PyTorch that takes two tensors as input and returns the sum of their elements. Test the function with 1D, 2D, and 3D tensors. This function will demonstrate how to perform element-wise addition between two tensors and then sum all elements of the resulting tensor.

In [22]:
# TensorFlow test tensors

# one-dimensional tensors
tensor1_tf = tf.constant([1, 2, 3])
tensor2_tf = tf.constant([4, 5, 6])

# two-dimensional tensors
tensor1_tf_2d = tf.constant([[1, 2], [3, 4]])
tensor2_tf_2d = tf.constant([[5, 6], [7, 8]])

tensor1_tf_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
tensor2_tf_3d = tf.constant([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])

# PyTorch test tensors

# one-dimensional tensors
tensor1_pt = torch.tensor([1, 2, 3])
tensor2_pt = torch.tensor([4, 5, 6])

# two-dimensional tensors
tensor1_pt_2d = torch.tensor([[1, 2], [3, 4]])
tensor2_pt_2d = torch.tensor([[5, 6], [7, 8]])

# three-dimensional tensors
tensor1_pt_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
tensor2_pt_3d = torch.tensor([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])


# Define the function in TensorFlow
def tensor_sum_tf(tensor1, tensor2):
    """Element-wise addition followed by sum of all elements."""
    return tf.reduce_sum(tensor1 + tensor2)


# Define the function in PyTorch
def tensor_sum_pt(tensor1, tensor2):
    """Element-wise addition followed by sum of all elements."""
    return torch.sum(tensor1 + tensor2)


# Test TensorFlow with 1D, 2D, and 3D tensors
print("TensorFlow 1D Tensor Sum:")
print(tensor_sum_tf(tensor1_tf, tensor2_tf))
print("--------------------------------")

print("TensorFlow 2D Tensor Sum:")
print(tensor_sum_tf(tensor1_tf_2d, tensor2_tf_2d))
print("--------------------------------")

print("TensorFlow 3D Tensor Sum:")
print(tensor_sum_tf(tensor1_tf_3d, tensor2_tf_3d))
print("--------------------------------")

# Test PyTorch with 1D, 2D, and 3D tensors
print("PyTorch 1D Tensor Sum:")
print(tensor_sum_pt(tensor1_pt, tensor2_pt))
print("--------------------------------")

print("PyTorch 2D Tensor Sum:")
print(tensor_sum_pt(tensor1_pt_2d, tensor2_pt_2d))
print("--------------------------------")

print("PyTorch 3D Tensor Sum:")
print(tensor_sum_pt(tensor1_pt_3d, tensor2_pt_3d))




TensorFlow 1D Tensor Sum:
tf.Tensor(21, shape=(), dtype=int32)
--------------------------------
TensorFlow 2D Tensor Sum:
tf.Tensor(36, shape=(), dtype=int32)
--------------------------------
TensorFlow 3D Tensor Sum:
tf.Tensor(136, shape=(), dtype=int32)
--------------------------------
PyTorch 1D Tensor Sum:
tensor(21)
--------------------------------
PyTorch 2D Tensor Sum:
tensor(36)
--------------------------------
PyTorch 3D Tensor Sum:
tensor(136)


## Part 2 of the Assignment:

The Role of Broadcasting in Tensor Operations

Broadcasting is a powerful mechanism that allows TensorFlow and PyTorch to work with tensors of different shapes during arithmetic operations.

2.1. Describe how broadcasting works in tensor operations, providing a simple example to illustrate your explanation.

Answer: 

Broadcasting allows tensors with different shapes to work together in element-wise operations. It automatically expands the smaller tensor along dimensions of size 1 or missing dimensions so that both tensors have compatible shapes. TensorFlow and PyTorch compare the dimensions from right to left. Two dimensions are compatible if they are the same size or if one of them is 1. In most cases, broadcasting does not create a new expanded tensor in memory. Instead, the operation is performed as if the smaller tensor had been repeated.


Example:
```python
# TensorFlow
a = tf.constant([[1, 2, 3],
                 [4, 5, 6]])   # shape (2, 3)
b = tf.constant([10, 20, 30])  # shape (3,)

# b is broadcast to shape (2, 3) and added row-wise
result = a + b
# [[11, 22, 33],
#  [14, 25, 36]]
```

2.2. Discuss why broadcasting is important and how it enhances the flexibility of tensor operations in building neural network models.

Answer: 

Broadcasting is important because neural networks often work with tensors that have different shapes and sizes. For example, a batch of activations may need to be combined with a bias vector or multiplied by a scalar learning rate. Without broadcasting, we would have to manually reshape or duplicate tensors before each operation. Broadcasting makes these operations simpler by automatically matching compatible dimensions. For example, a bias with shape `(features,)` can be added directly to a batch with shape `(batch_size, features)`. This makes the code shorter, reduces the risk of shape-related errors, and improves readability while keeping the mathematical operations clear.


2.3. Explain what limitations or challenges might arise when relying on broadcasting, particularly in the context of ensuring model correctness and efficiency.

Answer: 

One challenge of broadcasting is that it can cause silent shape mismatches. If two dimensions are neither the same size nor equal to 1, the operation will fail. However, broadcasting may also expand a tensor in an unintended way, allowing the code to run while producing incorrect results. For example, adding a vector of length 4 to a `(3, 4)` matrix is valid, but adding a vector of length 3 to the same matrix is not.

Even when broadcasting works correctly, it can hide logical mistakes, such as applying a bias to the wrong axis. In terms of performance, broadcasting may appear to be an inexpensive operation, but it can still require repeated access to the smaller tensor. In some cases, using `expand_dims`, `tile`, or `repeat` makes the code easier to understand and debug. In large neural network models, relying too much on implicit broadcasting can also make performance more difficult to analyze, especially on GPU or TPU hardware where memory access patterns affect efficiency.


In [ ]:
! pip install -q "nbconvert[webpdf]" playwright
! playwright install chromium

In [33]:
import shutil

NOTEBOOK = "assignment1.1_MostafaZamaniturk.ipynb"

# Save a named copy for submission if working from assignment1.1.ipynb
if NOTEBOOK != "assignment1.1.ipynb":
    shutil.copy("assignment1.1.ipynb", NOTEBOOK)

# Save the notebook to PDF (uses Chromium via Playwright; no LaTeX required)
!jupyter nbconvert --to webpdf {NOTEBOOK}

# Save the notebook to HTML
!jupyter nbconvert --to html {NOTEBOOK}

[NbConvertApp] Converting notebook assignment1.1_MostafaZamaniturk.ipynb to webpdf
[NbConvertApp] Building PDF
[NbConvertApp] PDF successfully created
[NbConvertApp] Writing 152335 bytes to assignment1.1_MostafaZamaniturk.pdf
[NbConvertApp] Converting notebook assignment1.1_MostafaZamaniturk.ipynb to html
[NbConvertApp] Writing 328160 bytes to assignment1.1_MostafaZamaniturk.html
