# In this notebook we are getting familiar with tensors in TensorFlow and PyTorch
* Getting information from tensors
* Tensors and Numpy
* Using tf.function

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.9.2


In [ ]:
# Let's create tensors with tf.constant
# Scalar
scalar=tf.constant(10)
print(scalar)
print(scalar.ndim)

# Vector
vector=tf.constant([12,12])
print(vector)
print(vector.ndim)

# Matrix
matrix=tf.constant([[12,12],[14,9]])
print(matrix)
print(matrix.ndim)

# Tensor
tensor=tf.constant([[[4,5,7],
                     [8,5,4]],
                    [[3,2,1],
                     [13,12,11]],
                    [[1,9,8],
                    [9,6,4]]])             
print(tensor)
print(tensor.ndim)

tf.Tensor(10, shape=(), dtype=int32)
0
tf.Tensor([12 12], shape=(2,), dtype=int32)
1
tf.Tensor(
[[12 12]
 [14  9]], shape=(2, 2), dtype=int32)
2
tf.Tensor(
[[[ 4  5  7]
  [ 8  5  4]]

 [[ 3  2  1]
  [13 12 11]]

 [[ 1  9  8]
  [ 9  6  4]]], shape=(3, 2, 3), dtype=int32)
3


In [ ]:
# you can create the same tensor with tf.Variable(). The difference between them is that you can change the element of tf.Variable()
# Vector
vector2=tf.Variable([12,12])
print(vector2)
vector3=vector2[0].assign(9)
print(vector3)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([12, 12], dtype=int32)>
<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 9, 12], dtype=int32)>


In [ ]:
# You can turn numpy arrays into tensors
import numpy as np
nump_a=np.arange(1,25, dtype=np.int32)
nump_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
tensor_a=tf.constant(nump_a)
tensor_a

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
tensor_b=tf.constant(nump_a, shape=(2,3,4))
tensor_b

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
import torch
print(torch.__version__)

1.13.1+cu116


In [ ]:
arr=np.array([3,4,7,1,5])
print(arr)
print(type(arr))

[3 4 7 1 5]
<class 'numpy.ndarray'>


In [ ]:
x=torch.from_numpy(arr)
print(type(x))

<class 'torch.Tensor'>


In [ ]:
# Let's do some Tensorflow and Pytorch implementation

In [ ]:
# Tensorflow
rank2_tf = tf.constant([[6, 5],
                             [4, 2],
                             [3, 1]], dtype=tf.int32)
print(rank2_tf)

tf.Tensor(
[[6 5]
 [4 2]
 [3 1]], shape=(3, 2), dtype=int32)


In [ ]:
# Pytorch
rank2_pt = torch.tensor([[6, 5],
                             [4, 2],
                             [3, 1]], dtype=torch.int32)
print(rank2_pt)

tensor([[6, 5],
        [4, 2],
        [3, 1]], dtype=torch.int32)


In [ ]:
# Some basic operations
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]])

a = tf.Variable(a)
b = tf.Variable(b)

print(tf.add(a, b), "n")
print(tf.multiply(a, b), "n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) n
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) n


In [ ]:
a = torch.tensor([1, 2, 3], dtype=torch.float)
b = torch.tensor([7, 8, 9], dtype=torch.float)

print(torch.add(a, b))
print(a.mul(b))

tensor([ 8., 10., 12.])
tensor([ 7., 16., 27.])
